name: widgets
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  assets:
    path: ../assets
  core:
    path: ../core
  dotted_border: ^2.0.0+3
  flutter:
    sdk: flutter
  image_cropper: ^3.0.1
  image_picker: ^0.8.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:                
                                      