name: assets
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: lib/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: lib/fonts/poppins/Poppins-Regular.ttf
          weight: 400

                    
                                      